### ISSUE TITLE
Release needed for FreeBSD Ports

### ISSUE THREAD

**Issue by ghost** [NitruxSA/flattr-icons#104]
Ehlo! Great icons there -- I am going to add a FreeBSD port, and that is only possible for releases -- hope for your understanding!

**Comment by UriHerrera** [comment]
I don't understand what you mean by "release". Did you meant a version release, like a stable version or similar? or a form release?.

If it's the first that's not likely to happen as there was never a "version 1.0" since it has been an on going work in progress from the beginning. You can place a version number as you wish in your port for FreeBSD if you need to.

**Comment by mike402** [comment]
On Fri, Jan 09, 2015 at 12:52:40PM -0800, Uri Herrera wrote:
> I don't understand what you mean by "release". Did you meant a version release, like a stable version or similar? or a form release?.

Release, as in associating commit ID with version number. It should not
necessarily mean "stable" -- just some remarkable point. This may be
appropriate time for, say, 0.1.0: I have not missed any icon so far!

> If it's the first that's not likely to happen as there was never a "version 1.0" since it has been an on going work in progress from the beginning. You can place a version number as you wish in your port for FreeBSD if you need to.

Ports only work with releases, due to the way they get files. I believe that is
true for other package managers, don't quote me on that though.

**Comment by UriHerrera** [comment]
Oh that, I didn't even noticed I could tag commits here. There's changes in the pipeline so those will have to happen first and then I'll tag a release.

**Comment by UriHerrera** [comment]
I've created a release: https://github.com/NitruxSA/flattr-icons/archive/v0.9-beta.zip - do note that this is the last for this version of the icons, I'm going to upload new ones.

**Comment by UriHerrera** [comment]
I've made a new release v1.0. You may port this for FreeBSD.

**Comment by mike402** [comment]
While testing it, I got the following errors:

install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/preferences-desktop-printer.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/javaws.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/preferences-desktop-peripherals.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/sun-java.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/pattern-kde4.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/kompare.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/liferea.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/kmousetool.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/pattern-kde.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/xame.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/xfcalendar.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/oracle_java7.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/java.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/korganizer.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/sun-java7.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/xfce4-session.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/sun-java6.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/openjdk-7.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/kdesvn.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/preferences-desktop-mouse.svg: No such file or directory
install: /tmp/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/sun-javaws.svg: No such file or directory

It appears those are caused by broken symlinks. For example, some point to "scalable" when there is no "scalable".

**Comment by UriHerrera** [comment]
I've tagged a new release, I've fixed the links there as well as adding more icons.

**Comment by mike402** [comment]
Still a couple errors:

install: /wrkdirs/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/preferences-desktop-peripherals.svg: No such file or directory
install: /wrkdirs/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/kmousetool.svg: No such file or directory
install: /wrkdirs/usr/ports/x11-themes/gnome-icons-flattr/work/flattr/apps/64/preferences-desktop-mouse.svg: No such file or directory

**Comment by UriHerrera** [comment]
Forgot to add the mouse icon.. whoops. Added: https://github.com/NitruxSA/flattr-icons/commit/7302991ef024b8148683ca797c2ec433824c9e98
