### ISSUE TITLE
 Earlier versions Were the better than 1.0

### ISSUE THREAD

**Issue by gnurichard** [NitruxSA/flattr-icons#105]
is just my personal opinion, but the artwork you had in earlier versions of flattr seemed to me much better, more enjoyable and implmentables icons both KDE and gtk systems, the current work seems immature and lacking in personality already had the project, hopefully draw back parts of the previous job as beautiful icons from folders you wore using since the beginning of development. do an excellent art work and hopefully follow so.

**Comment by UriHerrera** [comment]
An older version is there for purely historical purposes (check the releases link in the front page) and like we've said in the release announcement: we won't support it, fix it or maintain that version.

====

The previous icons were turning into a dull theme. They began to lack in many areas, they were flat, yes, but they were *too flat*. They had technical problems like not being aligned to the grid, they were still very incomplete, even less now because of the redesign (something that eventually will be fixed). They were overly angular, and they mostly still are but that will probably change later on. The included scripts to change the folder colors were a bit complicated, they're now simpler and most importantly there's only *one* now.

Notably the icons are now sharper, they're now higher res, they use more colors now, they have distinctive shapes now instead of the background+logo approach of old (which many, many icons had), etc.

And last but not least, **I actually like them again**.

====

*The folders were the very first thing I changed*.

**Comment by sksmfjsduausjdfl** [comment]
That's simply an opinion. Personally, I think the update is *fantastic* and Uri is right in saying that the initial icons had certain flaws.
